version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quiz_admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: quiz
