version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quiz_admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: quiz
    volumes:
      - db_value:/var/lib/postgresql/data/
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  db_value: